#@TYPE: Machine
#@NAME: RaspberryPi Zero Development Board
#@DESCRIPTION: Machine configuration for the RaspberryPi Zero board (https://www.raspberrypi.org/blog/raspberry-pi-zero)

MACHINEOVERRIDES =. "raspberrypi:"
include conf/machine/raspberrypi.conf

SERIAL_CONSOLES ?= "115200;ttyAMA0"

#
# Below are variables ONLY needed for running with Yocto/OE's runqemu script
#
IMAGE_CLASSES += "qemuboot"

QB_SYSTEM_NAME = "qemu-system-arm"
QB_MACHINE = "-machine raspi0"
QB_MEM = "-m 512"
QB_DTB = "bcm2708-rpi-zero.dtb"
QB_NETWORK_DEVICE = "-device usb-net,netdev=net0,mac=@MAC@"
QB_KERNEL_ROOT = "/dev/sda"
# The dwc_otg.fiq_fsm_enable setting is necessary to get USB devices (both disk and net) working.  Without this, boot hangs
# The initcall_blacklist=bcm2835_pm_driver_init is needed to workaround boot issues.  Seems like the PM HW emulation isn't present
QB_KERNEL_CMDLINE_APPEND = "rootwait initcall_blacklist=bcm2835_pm_driver_init earlycon=pl011,0x20201000 dwc_otg.fiq_fsm_enable=0"
QB_RNG = ""
QB_ROOTFS_OPT = "-drive id=disk0,file=@ROOTFS@,if=none,format=raw -device usb-storage,drive=disk0"
QB_DEFAULT_FSTYPE = "ext3"
